### ISSUE TITLE
SyntaxError: Unexpected token ':', ": {"id":"c"... is not valid JSON...

### ISSUE THREAD

**Issue by VisionTheta** [yakGPT/yakGPT#96] opened 2024-01-31 09:23 UTC
yakGPT suddenly cannot work normally as usual when using apis like GPT4. However, I tested with chatgpt 3.5 model and it worked as usual.

I have tried with official deployment at yakgpt.vercel.app on different browers and they all failed. And I could get normal result using official curl post and I'm sure that my API has permission to access GPT 4 API.

The log info in the developer console is shown as follows:

```
_app-c9c65ec057b5d078.js:50024 SyntaxError: Unexpected token ':', ": {"id":"c"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.IncomingMessage.<anonymous> (_app-c9c65ec057b5d078.js:50024:53683)
    at a.emit (_app-c9c65ec057b5d078.js:50024:61155)
    at R (_app-c9c65ec057b5d078.js:50024:120366)
    at P (_app-c9c65ec057b5d078.js:50024:120195)
    at E.push (_app-c9c65ec057b5d078.js:50024:123102)
    at _app-c9c65ec057b5d078.js:50024:156301
    at new Promise (<anonymous>)
    at Object.write (_app-c9c65ec057b5d078.js:50024:156256)
```

**Comment by Big-ol-Bob** [comment] 2024-01-31 18:22
Same issue, for at least 2-3 days now for me.  Exclusively using main version hosted on vercel.app recently, have not built my own in a long time.  Appears to happen consistently with the newer engines e.g. gpt-4-1106-preview, gpt-4-0125-preview, and gpt-4.  It will output just a couple words and stop, and the console will show errors similar or identical to above as per VisionTheta.  Sometimes it seems better with legacy engines e.g. -0314 or -0613, but not consistently because those may throw errors too.

I wonder if something with the timing has changed? ... Because it appears sometimes I will see the errors in the console but then it somehow corrects and manages to move forward and to continue outputting text; it's almost as if it's trying to process the output before the JSON is fully saved to local storage or something like that.  I have not managed to catch it with an actual incorrectly formatted JSON in the local storage but I may see if I can do that.

**Comment by Big-ol-Bob** [comment] 2024-01-31 18:38
> Same issue, for at least 2-3 days now for me. Exclusively using main version hosted on vercel.app recently, have not built my own in a long time. Appears to happen consistently with the newer engines e.g. gpt-4-1106-preview, gpt-4-0125-preview, and gpt-4. It will output just a couple words and stop, and the console will show errors similar or identical to above as per VisionTheta. Sometimes it seems better with legacy engines e.g. -0314 or -0613, but not consistently because those may throw errors too.
> 
> I wonder if something with the timing has changed? ... Because it appears sometimes I will see the errors in the console but then it somehow corrects and manages to move forward and to continue outputting text; it's almost as if it's trying to process the output before the JSON is fully saved to local storage or something like that. I have not managed to catch it with an actual incorrectly formatted JSON in the local storage but I may see if I can do that.
> 
> SyntaxError: Unexpected token ':', ": {"id":"c"... is not valid JSON at JSON.parse () at t.IncomingMessage. (_app-c9c65ec057b5d078.js:50024:53683) at a.emit (_app-c9c65ec057b5d078.js:50024:61155) at R (_app-c9c65ec057b5d078.js:50024:120366) at P (_app-c9c65ec057b5d078.js:50024:120195) at E.push (_app-c9c65ec057b5d078.js:50024:123102) at _app-c9c65ec057b5d078.js:50024:156301 at new Promise () at Object.write (_app-c9c65ec057b5d078.js:50024:156256)
> 
> SyntaxError: Unexpected token ':', ": [DONE]" is not valid JSON at JSON.parse () at t.IncomingMessage. (_app-c9c65ec057b5d078.js:50024:53683) at a.emit (_app-c9c65ec057b5d078.js:50024:61155) at R (_app-c9c65ec057b5d078.js:50024:120366) at P (_app-c9c65ec057b5d078.js:50024:120195) at E.push (_app-c9c65ec057b5d078.js:50024:123102) at _app-c9c65ec057b5d078.js:50024:156301 at new Promise () at Object.write (_app-c9c65ec057b5d078.js:50024:156256)


There are other clues as well.  E.g. if you look in the JSON the assistant reply might start with a space character or a period followed by a space, as if the beginning of the message is missing too.

**Comment by Big-ol-Bob** [comment] 2024-01-31 19:25
Seems to be a consistent pattern based on the length of reply or the time it takes to output a reply.

Based on just a handful of trials with gpt-4, it will consistently give one word answers, sometimes will do two words but sometimes not, will less often successfully give three word or longer replies, etc. At most I have gotten it once to give a paragraph, but I have not gotten it to give "two brief paragraphs." I will just hit the refresh button in the reply box to keep trying it for a given prompt.

```

            {
                "id": "06dd5e2a-0364-47d2-b51f-262e3cafc813",
                "title": "",
                "messages": [
                    {
                        "id": "aecea92b-d9f7-498f-8a8f-3b09f65d9c4c",
                        "content": "Give a one word response.",
                        "role": "user"
                    },
                    {
                        "id": "ef04d846-8d3c-4064-978c-96aefd07dec7",
                        "content": "Sure.",
                        "role": "assistant",
                        "loading": false
                    },
                    {
                        "id": "253134dd-c942-43b7-815b-67b56aa67d77",
                        "content": "Give a two word response.",
                        "role": "user"
                    },
                    {
                        "id": "cdc1dd0c-29b1-41fa-9931-0221e07a6bd8",
                        "content": "Of course.",
                        "role": "assistant",
                        "loading": false
                    },
                    {
                        "id": "589fc8d4-e492-45a7-be80-374518e5bb01",
                        "content": " Give a three word response. ",
                        "role": "user"
                    },
                    {
                        "id": "039363eb-874e-4ee6-b29a-fc9054723919",
                        "content": "",
                        "role": "assistant",
                        "loading": false
                    }

```

```

                    {
                        "id": "aecea92b-d9f7-498f-8a8f-3b09f65d9c4c",
                        "content": "Give a one word response.",
                        "role": "user"
                    },
                    {
                        "id": "ef04d846-8d3c-4064-978c-96aefd07dec7",
                        "content": "Sure.",
                        "role": "assistant",
                        "loading": false
                    },
                    {
                        "id": "253134dd-c942-43b7-815b-67b56aa67d77",
                        "content": "Give a two word response.",
                        "role": "user"
                    },
                    {
                        "id": "cdc1dd0c-29b1-41fa-9931-0221e07a6bd8",
                        "content": "Of course.",
                        "role": "assistant",
                        "loading": false
                    },
                    {
                        "id": "589fc8d4-e492-45a7-be80-374518e5bb01",
                        "content": " Give a three word response. ",
                        "role": "user"
                    },
                    {
                        "id": "62755214-b5c2-43c3-993c-6f7e3f933681",
                        "content": "Absolutely, no problem.",
                        "role": "assistant",
                        "loading": false
                    },
                    {
                        "id": "f3d8e6ee-65d1-410f-aba4-afca0a1bc93c",
                        "content": "4?",
                        "role": "user"
                    },
                    {
                        "id": "f380f9d6-a01d-4d57-99a6-ee69a33cb0f5",
                        "content": "I can do that.",
                        "role": "assistant",
                        "loading": false
                    },
                    {
                        "id": "486bb7b4-3469-4c1f-b50f-2b0d68a5ece7",
                        "content": "5 words",
                        "role": "user"
                    },
                    {
                        "id": "010ea388-05fe-44aa-adc8-d6efa81697ec",
                        "content": "I am here to assist you.",
                        "role": "assistant",
                        "loading": false
                    },
                    {
                        "id": "4c431f06-8426-4fbc-9b4b-8c14fdbca04b",
                        "content": "10 words",
                        "role": "user"
                    },
                    {
                        "id": "f3b993c2-dad1-4d00-9ff6-b9ba8e72b1cc",
                        "content": "Sure, I am here to provide any assistance you need.",
                        "role": "assistant",
                        "loading": false
                    },
                    {
                        "id": "e7bba186-d589-4232-82a2-c4259a88cd9d",
                        "content": "two brief paragraphs",
                        "role": "user"
                    },
                    {
                        "id": "47035822-da96-4b27-93cb-1d401dcc33b0",
                        "content": " OpenAI.",
                        "role": "assistant",
                        "loading": false
                    }

```

**Comment by rannmann** [comment] 2024-02-01 17:36
I'm guessing the streaming format has changed in some way, and yakgpt made an incorrect assumption about it always being complete and valid json.

This issue seems intermittent to me (becoming more frequent), but none of the other chatgpt integrations I use are affected, even though some of them use the streamed response as well.  It might be good to look through the official js repo to see if they've done anything recently regarding streaming changes: https://github.com/openai/openai-node/releases

**Comment by rannmann** [comment] 2024-02-01 18:18
Okay, it's an easy fix.  Yakgpt assumed the messages started with `data:` and sometimes it starts with ` data:` (see whitespace).

Simply trim the message before parsing and it's fixed.

**Comment by TechnoFairyGirl** [comment] 2024-02-01 22:22
The [official deployment](https://yakgpt.vercel.app/) does not work at all for me, and I am seeing the same symptoms mentioned here. The patch by @rannmann resolves the issue for me (tested via the [Vercel preview](https://yak-gpt-git-fork-rannmann-patch-1-yakgpt.vercel.app/) linked in the PR). I will continue to use the aforementioned preview until the issues is resolved in the official version.

**Comment by yannleretaille** [comment] 2024-02-02 17:35
Do note that these characters are not random - in these case those seem to be trailing new lines, which are used in the SSE event protocol. The correct fix would be to use a proper SSE library for communicating with the streaming endpoint or the official Openai node library, which comes with their own [SSEDecoder](https://github.com/openai/openai-node/blob/master/src/streaming.ts#L209) implementation.

**Comment by rannmann** [comment] 2024-02-02 19:03
That's definitely a better solution.  Think of mine as a quick hotfix in the meantime.  Adding a `trim()` is low-risk, and adding a library is a bit more involved.

If you get a working MR done with that change before this one is merged in, we can skip mine.

**Comment by dev-msp** [comment] 2024-02-05 03:31
> The correct fix would be to use a proper SSE library for communicating with the streaming endpoint or the official Openai node library, which comes with their own [SSEDecoder](https://github.com/openai/openai-node/blob/master/src/streaming.ts#L209) implementation.

The one caveat here is that YakGPT is entirely client-side by design. The app itself is a static site; no API that handles user data. That's how everyone's data stays private to their browser session. So that would rule out backend-only libraries.

**Comment by yakGPT** [comment] 2024-02-05 15:38
Thank you guys so much for debugging and fixing this! Warms my heart really <3 

I'm quite busy with RL stuff atm but if any of you wanna switch to a proper SSE library (I know my implementation is so janky) I would really love that!

**Closed** 2024-02-05 15:37 UTC
